### ISSUE TITLE
make changes backward compatible between minor releases

### ISSUE THREAD

**Issue by AlexisAnzieu** [DoneDeal0/superdiff#13]
Hey,
Glad to see that the project is receiving continuous improvement! 

I am using this lib in a CI / CD pipeline, so changing `discardArrayOrder` to `ignoreArrayOrder` in the last update broke the flow. 
Would it be possible to keep parameter names backward compatible between minor releases? 
Not a big deal but im wondering if we could beneficiate of code improvement without being worried about breaking change.

Thanks a lot!

**Comment by DoneDeal0** [comment]
Hi @AlexisAnzieu,

First of all, thank you so much for the 3 coffees you bought to support Superdiff, I really appreciate it 👍! 

As for the upgrade, I'm sorry it broke your pipeline. I always make sure to publish a note with a list of breaking changes for each release. I thought renaming `discardArrayOrder` to `ignoreArrayOrder` was necessary because the wording was poorly chosen. To avoid too frequent updates, I decided to include this change in `v1.0.9`. 

However, I can assure you that I don't plan to introduce any more breaking changes in the future. You can use the current and upcoming versions of Superdiff with complete peace of mind^^.

Again, my apologies for the inconvenience.

**Comment by AlexisAnzieu** [comment]
Sounds great! Thank you 🙏
