### ISSUE TITLE
Hello, is the benchMark on readme the data of object diff? I want to know the performance of array diff (getListDiff), do you have relevant benchmark data

### ISSUE THREAD

**Issue by linjunc** [DoneDeal0/superdiff#2]

**Comment by DoneDeal0** [comment]
Hi @linjunc ,

There is no benchmark for the arrays because I don't know any lib that does a complete array diff like `Superdiff`.

However, here are the performances of `Superdiff` for arrays:

| quantity   | array of strings | array of objects |
| --------- | ------------ | ------------ |
| 1.000     | 6.09ms      |20.21ms       |
| 10.000    | 17.87ms      | 136.89ms      |
| 100.000   | 56.90ms     | 1282.66ms      |
| 1.000.000 | 423.36ms    | 12416.07ms     |

**Comment by linjunc** [comment]
OK, I understand Thank you for your answer

**Comment by DoneDeal0** [comment]
@linjunc This issue is 3 years old, but just in case, I inform you that significant performance improvements have been shipped.

## 📊 BENCHMARK

Environment: Node.js 24.12.0 (LTS) • MacBook Pro M2 (2023, Sequoia 15.1) • 16GB RAM. 

Method: Warm up runs, then each script is executed 20 times, and we keep the median time. To minimize garbage collection and cross‑benchmark interference, all scenarios are run individually. All benchmark scripts are included so you can reproduce the results locally.

### List diff

| Scenario                  | superdiff     | arr-diff   | deep-diff |
| ------------------------- | ------------- | ---------- | --------- |
| 10k items array           | **1.84 ms**   | 32.95 ms   | 4.74 ms   |
| 100k items array          | **17.43 ms**  | 3363.15 ms | 50.36 ms  |

### Object diff

| Scenario                       | superdiff | deep-object-diff | deep-diff | microdiff  |
| ------------------------------ | --------- | ---------------- | --------- | ---------- |
| 10k flat object keys           | 2.27 ms   | 2.44 ms          | 39.37 ms  | **2.24 ms**|
| 100k flat object keys          | **29.23 ms**  | 31.86 ms     | 3784.50 ms| 29.51 ms   |
| 100k nested nodes              | **4.25 ms**   | 9.67 ms      | 16.51 ms  | 7.26 ms    |

### Text diff

| Scenario                | superdiff    | diff       |
| ----------------------- | ------------ | ---------- |
| 10k words               | **1.38 ms**  | 3.86 ms    | 
| 100k words              | **21.68 ms** | 45.93 ms   | 
| 10k sentences           | **2.30 ms**  | 5.61 ms    |
| 100k sentences          | **21.95 ms** | 62.03 ms   |

<sub>(Superdiff uses its `normal` accuracy settings to match diff's behavior)</sub>
